#!/usr/bin/env python3
"""Initialize empty bridge files so /auto Session Start Protocol does not break.

Creates (idempotent — never overwrites existing files):
  logs/orchestrator_state.json   (or seeds metric/phase from competition_meta.yaml)
  logs/experiment_digest.md      (empty skeleton)
  logs/insights.jsonl            (empty)
  logs/cycle_history.jsonl       (empty)
  logs/agent_messages.jsonl      (empty)

Run once at project setup, or any time a bridge file is missing.
"""

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ROOT = Path(__file__).resolve().parent.parent
LOGS = ROOT / "logs"
META = ROOT / "competition_meta.yaml"


def load_meta():
    if yaml is None or not META.exists():
        return {}
    with META.open() as f:
        return yaml.safe_load(f) or {}


def init_orchestrator_state(meta: dict) -> None:
    path = LOGS / "orchestrator_state.json"
    if path.exists():
        # Backfill missing fields without clobbering existing data.
        try:
            current = json.loads(path.read_text())
        except json.JSONDecodeError:
            current = {}
        defaults = _state_defaults(meta)
        changed = False
        for k, v in defaults.items():
            if k not in current:
                current[k] = v
                changed = True
        if changed:
            path.write_text(json.dumps(current, indent=2, ensure_ascii=False))
            print(f"[backfill] {path}")
        else:
            print(f"[ok]       {path}")
        return
    path.write_text(json.dumps(_state_defaults(meta), indent=2, ensure_ascii=False))
    print(f"[create]   {path}")


def _state_defaults(meta: dict) -> dict:
    comp = meta.get("competition", {})
    return {
        "last_updated": None,
        "current_phase": "baseline",
        "best_cv": 0.0,
        "best_experiment": None,
        "stall_counter": 0,
        "total_cycles": 0,
        "max_cycles": 20,
        "strategy_history": [],
        "next_action": "plan",
        "active_experiments": [],
        "blocked_approaches": [],
        "recent_context_window": 5,
        "last_reasoning": "",
        "competition_metric": comp.get("metric"),
        "num_classes": comp.get("num_classes"),
        "data_shape": None,
    }


def init_digest() -> None:
    path = LOGS / "experiment_digest.md"
    if path.exists():
        print(f"[ok]       {path}")
        return
    skeleton = (
        "# Experiment Digest\n\n"
        "> Auto-regenerated by `scripts/build_digest.py` after every cycle.\n"
        "> Read by Session Start Protocol Step 3.\n\n"
        "## Current Best\n"
        "- best_cv_macro_f1: n/a\n"
        "- best_experiment: n/a\n"
        "- best_lb: n/a\n\n"
        "## Recent Experiments\n"
        "| exp_id | model | features | cv_macro_f1 | cv_std | lb | status |\n"
        "|---|---|---|---|---|---|---|\n"
        "| (empty — run /auto or /plan to populate) |  |  |  |  |  |  |\n"
    )
    path.write_text(skeleton)
    print(f"[create]   {path}")


def init_empty_jsonl(name: str) -> None:
    path = LOGS / name
    if path.exists():
        print(f"[ok]       {path}")
        return
    path.write_text("")
    print(f"[create]   {path}")


def main():
    LOGS.mkdir(parents=True, exist_ok=True)
    meta = load_meta()
    init_orchestrator_state(meta)
    init_digest()
    for fname in ("insights.jsonl", "cycle_history.jsonl", "agent_messages.jsonl"):
        init_empty_jsonl(fname)
    print("\nBridge files ready. /auto Session Start Protocol Steps 2-4 will not break.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
